export const SocketEvents = {
  DOUBT_LIST: 'DOUBT_LIST',
  NEW_DOUBT_REQUEST: 'NEW_DOUBT_REQUEST',
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_ENDED: 'SESSION_ENDED',
  SESSION_EXTENDED: 'SESSION_EXTENDED',
  WALLET_UPDATED: 'WALLET_UPDATED',
  DIRECT_ACCEPTED: 'DIRECT_ACCEPTED',
  DIRECT_REJECTED: 'DIRECT_REJECTED',
  POOL_DOUBT_ACCEPTED: 'POOL_DOUBT_ACCEPTED',
};